apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-secret
stringData:
  accessKeyID: MyMegaSecretID
  secretAccessKey: MyMegaSecretKey
  # For AWS set it to "https://s3.<region>.amazonaws.com"
  endpoint: https://storage.yandexcloud.net
  # If not on S3, set it to ""
  region: ""