apiVersion: v1
kind: Namespace
metadata:
  name: homework

---

apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: homework
  labels:
    app.kubernetes.io/name: myapp
spec:
  containers:
  - name: myapp
    image: nginx:stable-alpine3.21
    ports:
      - containerPort: 80
