---

apiVersion: v1
kind: Namespace
metadata:
  name: operators
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: operators
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
    spec:
      serviceAccountName: mysql-operator
      containers:
      - name: mysql-operator
        image: roflmaoinmysoul/mysql-operator:1.0.0
        imagePullPolicy: Never
