---

apiVersion: v1
kind: Namespace
metadata:
  name: demo

---

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: demo
  name: vault-auth
  labels:
    app: vault-agent-demo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: demo
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: vault-auth-toke
  namespace: demo
  annotations:
    kubernetes.io/service-account.name: vault-auth
