apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: demo
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200" 
      path: "otus" 
      version: "v2" 
      auth:
        kubernetes: 
          mountPath: "kubernetes"
          role: "otus" 
          serviceAccountRef:
            name: "vault-auth" 
