---
global:
  enabled: true
  tlsDisable: false

server:
  enabled: true
  image:
    repository: "hashicorp/vault"
    tag: "1.20.1"
    pullPolicy: IfNotPresent

  ha:
    enabled: true
    replicas: 3

    config: |
      ui = true
      api_addr = "http://POD_IP:8200"
      listener "tcp" {
          tls_disable = 1
          address     = "0.0.0.0:8200"
      }

      storage "consul" {
          path = "vault/"
          address = "consul-consul-server.svc.vault.cluster.local:8500"
      }

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: ""
    accessMode: ReadWriteOnce

  service:
    enabled: true

ui:
  enabled: true
  publishNotReadyAddresses: true
  activeVaultPodOnly: false
  serviceType: "ClusterIP"
  externalPort: 8200
  targetPort: 8200
