---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: init-dir-pvc
  namespace: homework
spec:
  storageClassName: "mynewclass"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: init-dir-pv
  namespace: homework
spec:
  capacity:
    storage: 1Gi
  storageClassName: "mynewclass"
  claimRef:
    name: init-dir-pvc
    namespace: homework
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
